# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pi_image.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1283, 685)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 0, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(60, 640, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_status.setFont(font)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 1261, 611))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_control = QtWidgets.QWidget()
        self.tab_control.setObjectName("tab_control")
        self.control_tableWidget_info = QtWidgets.QTableWidget(self.tab_control)
        self.control_tableWidget_info.setGeometry(QtCore.QRect(10, 40, 1231, 401))
        self.control_tableWidget_info.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.control_tableWidget_info.setObjectName("control_tableWidget_info")
        self.control_tableWidget_info.setColumnCount(11)
        self.control_tableWidget_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.control_tableWidget_info.setHorizontalHeaderItem(10, item)
        self.control_pushButton_capture = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_capture.setGeometry(QtCore.QRect(740, 460, 271, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_capture.setFont(font)
        self.control_pushButton_capture.setObjectName("control_pushButton_capture")
        self.label = QtWidgets.QLabel(self.tab_control)
        self.label.setGeometry(QtCore.QRect(340, 0, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.control_pushButton_camReboot = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_camReboot.setGeometry(QtCore.QRect(460, 460, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_camReboot.setFont(font)
        self.control_pushButton_camReboot.setObjectName("control_pushButton_camReboot")
        self.control_pushButton_camStop = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_camStop.setGeometry(QtCore.QRect(460, 520, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_camStop.setFont(font)
        self.control_pushButton_camStop.setObjectName("control_pushButton_camStop")
        self.control_pushButton_refreshSysStat = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_refreshSysStat.setGeometry(QtCore.QRect(1030, 460, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_refreshSysStat.setFont(font)
        self.control_pushButton_refreshSysStat.setObjectName("control_pushButton_refreshSysStat")
        self.control_textEdit_expectedPiList = QtWidgets.QTextEdit(self.tab_control)
        self.control_textEdit_expectedPiList.setGeometry(QtCore.QRect(10, 480, 431, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.control_textEdit_expectedPiList.setFont(font)
        self.control_textEdit_expectedPiList.setObjectName("control_textEdit_expectedPiList")
        self.label_5 = QtWidgets.QLabel(self.tab_control)
        self.label_5.setGeometry(QtCore.QRect(10, 450, 431, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.control_pushButton_GPIOon = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_GPIOon.setGeometry(QtCore.QRect(1030, 520, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_GPIOon.setFont(font)
        self.control_pushButton_GPIOon.setObjectName("control_pushButton_GPIOon")
        self.control_pushButton_GPIOoff = QtWidgets.QPushButton(self.tab_control)
        self.control_pushButton_GPIOoff.setGeometry(QtCore.QRect(1140, 520, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.control_pushButton_GPIOoff.setFont(font)
        self.control_pushButton_GPIOoff.setObjectName("control_pushButton_GPIOoff")
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.config_tableWidget_cameraConfN = QtWidgets.QTableWidget(self.tab_config)
        self.config_tableWidget_cameraConfN.setGeometry(QtCore.QRect(10, 30, 261, 441))
        self.config_tableWidget_cameraConfN.setObjectName("config_tableWidget_cameraConfN")
        self.config_tableWidget_cameraConfN.setColumnCount(1)
        self.config_tableWidget_cameraConfN.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfN.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.config_tableWidget_cameraConfN.setItem(0, 0, item)
        self.config_tableWidget_delayConf = QtWidgets.QTableWidget(self.tab_config)
        self.config_tableWidget_delayConf.setGeometry(QtCore.QRect(570, 30, 331, 441))
        self.config_tableWidget_delayConf.setObjectName("config_tableWidget_delayConf")
        self.config_tableWidget_delayConf.setColumnCount(1)
        self.config_tableWidget_delayConf.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_delayConf.setHorizontalHeaderItem(0, item)
        self.config_label_status = QtWidgets.QLabel(self.tab_config)
        self.config_label_status.setGeometry(QtCore.QRect(170, 530, 1041, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.config_label_status.setFont(font)
        self.config_label_status.setText("")
        self.config_label_status.setObjectName("config_label_status")
        self.config_pushButton_cameraConf = QtWidgets.QPushButton(self.tab_config)
        self.config_pushButton_cameraConf.setGeometry(QtCore.QRect(170, 480, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.config_pushButton_cameraConf.setFont(font)
        self.config_pushButton_cameraConf.setObjectName("config_pushButton_cameraConf")
        self.label_3 = QtWidgets.QLabel(self.tab_config)
        self.label_3.setGeometry(QtCore.QRect(80, -1, 721, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.config_tableWidget_cameraConfP = QtWidgets.QTableWidget(self.tab_config)
        self.config_tableWidget_cameraConfP.setGeometry(QtCore.QRect(290, 30, 261, 441))
        self.config_tableWidget_cameraConfP.setObjectName("config_tableWidget_cameraConfP")
        self.config_tableWidget_cameraConfP.setColumnCount(1)
        self.config_tableWidget_cameraConfP.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.config_tableWidget_cameraConfP.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.config_tableWidget_cameraConfP.setItem(0, 0, item)
        self.label_4 = QtWidgets.QLabel(self.tab_config)
        self.label_4.setGeometry(QtCore.QRect(1010, 0, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.config_textEdit_projector = QtWidgets.QTextEdit(self.tab_config)
        self.config_textEdit_projector.setGeometry(QtCore.QRect(940, 30, 281, 281))
        self.config_textEdit_projector.setReadOnly(True)
        self.config_textEdit_projector.setObjectName("config_textEdit_projector")
        self.config_pushButton_projectorSync = QtWidgets.QPushButton(self.tab_config)
        self.config_pushButton_projectorSync.setGeometry(QtCore.QRect(950, 320, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.config_pushButton_projectorSync.setFont(font)
        self.config_pushButton_projectorSync.setObjectName("config_pushButton_projectorSync")
        self.config_pushButton_rebootPi = QtWidgets.QPushButton(self.tab_config)
        self.config_pushButton_rebootPi.setGeometry(QtCore.QRect(940, 490, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.config_pushButton_rebootPi.setFont(font)
        self.config_pushButton_rebootPi.setObjectName("config_pushButton_rebootPi")
        self.config_pushButton_shutdownPi = QtWidgets.QPushButton(self.tab_config)
        self.config_pushButton_shutdownPi.setGeometry(QtCore.QRect(1080, 490, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.config_pushButton_shutdownPi.setFont(font)
        self.config_pushButton_shutdownPi.setObjectName("config_pushButton_shutdownPi")
        self.config_checkBox_confirmReboot = QtWidgets.QCheckBox(self.tab_config)
        self.config_checkBox_confirmReboot.setGeometry(QtCore.QRect(940, 460, 271, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.config_checkBox_confirmReboot.setFont(font)
        self.config_checkBox_confirmReboot.setObjectName("config_checkBox_confirmReboot")
        self.tabWidget.addTab(self.tab_config, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.prev_graphicsView_1 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_1.setGeometry(QtCore.QRect(0, 20, 351, 261))
        self.prev_graphicsView_1.setObjectName("prev_graphicsView_1")
        self.prev_graphicsView_5 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_5.setGeometry(QtCore.QRect(360, 290, 351, 271))
        self.prev_graphicsView_5.setObjectName("prev_graphicsView_5")
        self.prev_graphicsView_4 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_4.setGeometry(QtCore.QRect(0, 290, 351, 271))
        self.prev_graphicsView_4.setObjectName("prev_graphicsView_4")
        self.prev_graphicsView_2 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_2.setGeometry(QtCore.QRect(360, 20, 351, 261))
        self.prev_graphicsView_2.setObjectName("prev_graphicsView_2")
        self.prev_comboBox_count = QtWidgets.QComboBox(self.tab)
        self.prev_comboBox_count.setGeometry(QtCore.QRect(1090, 20, 151, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.prev_comboBox_count.setFont(font)
        self.prev_comboBox_count.setObjectName("prev_comboBox_count")
        self.prev_lineEdit_ids = QtWidgets.QLineEdit(self.tab)
        self.prev_lineEdit_ids.setGeometry(QtCore.QRect(1090, 111, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prev_lineEdit_ids.setFont(font)
        self.prev_lineEdit_ids.setObjectName("prev_lineEdit_ids")
        self.prev_pushButton_preview = QtWidgets.QPushButton(self.tab)
        self.prev_pushButton_preview.setGeometry(QtCore.QRect(1100, 230, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prev_pushButton_preview.setFont(font)
        self.prev_pushButton_preview.setObjectName("prev_pushButton_preview")
        self.prev_progressBar = QtWidgets.QProgressBar(self.tab)
        self.prev_progressBar.setGeometry(QtCore.QRect(1090, 380, 151, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.prev_progressBar.setFont(font)
        self.prev_progressBar.setProperty("value", 0)
        self.prev_progressBar.setObjectName("prev_progressBar")
        self.prev_label_status = QtWidgets.QLabel(self.tab)
        self.prev_label_status.setGeometry(QtCore.QRect(1090, 350, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.prev_label_status.setFont(font)
        self.prev_label_status.setObjectName("prev_label_status")
        self.prev_graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_3.setGeometry(QtCore.QRect(720, 20, 351, 261))
        self.prev_graphicsView_3.setObjectName("prev_graphicsView_3")
        self.prev_graphicsView_6 = QtWidgets.QGraphicsView(self.tab)
        self.prev_graphicsView_6.setGeometry(QtCore.QRect(720, 290, 351, 271))
        self.prev_graphicsView_6.setObjectName("prev_graphicsView_6")
        self.prev_pushButton_refreshList = QtWidgets.QPushButton(self.tab)
        self.prev_pushButton_refreshList.setGeometry(QtCore.QRect(1090, 60, 151, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prev_pushButton_refreshList.setFont(font)
        self.prev_pushButton_refreshList.setObjectName("prev_pushButton_refreshList")
        self.prev_radioButton_normal = QtWidgets.QRadioButton(self.tab)
        self.prev_radioButton_normal.setGeometry(QtCore.QRect(1100, 160, 131, 20))
        self.prev_radioButton_normal.setChecked(True)
        self.prev_radioButton_normal.setObjectName("prev_radioButton_normal")
        self.prev_radioButton_projected = QtWidgets.QRadioButton(self.tab)
        self.prev_radioButton_projected.setGeometry(QtCore.QRect(1100, 200, 131, 20))
        self.prev_radioButton_projected.setObjectName("prev_radioButton_projected")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.prev_pushButton_download = QtWidgets.QPushButton(self.tab_2)
        self.prev_pushButton_download.setGeometry(QtCore.QRect(540, 400, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prev_pushButton_download.setFont(font)
        self.prev_pushButton_download.setObjectName("prev_pushButton_download")
        self.prev_progressBar_D = QtWidgets.QProgressBar(self.tab_2)
        self.prev_progressBar_D.setGeometry(QtCore.QRect(450, 540, 381, 23))
        self.prev_progressBar_D.setProperty("value", 0)
        self.prev_progressBar_D.setObjectName("prev_progressBar_D")
        self.prev_label_status_D = QtWidgets.QLabel(self.tab_2)
        self.prev_label_status_D.setGeometry(QtCore.QRect(450, 510, 731, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.prev_label_status_D.setFont(font)
        self.prev_label_status_D.setObjectName("prev_label_status_D")
        self.down_tableWidget_D = QtWidgets.QTableWidget(self.tab_2)
        self.down_tableWidget_D.setGeometry(QtCore.QRect(10, 10, 1231, 301))
        self.down_tableWidget_D.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.down_tableWidget_D.setRowCount(0)
        self.down_tableWidget_D.setColumnCount(2)
        self.down_tableWidget_D.setObjectName("down_tableWidget_D")
        item = QtWidgets.QTableWidgetItem()
        self.down_tableWidget_D.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.down_tableWidget_D.setHorizontalHeaderItem(1, item)
        self.prev_pushButton_delete = QtWidgets.QPushButton(self.tab_2)
        self.prev_pushButton_delete.setGeometry(QtCore.QRect(1060, 370, 171, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prev_pushButton_delete.setFont(font)
        self.prev_pushButton_delete.setObjectName("prev_pushButton_delete")
        self.prev_checkBox_confirmDelete = QtWidgets.QCheckBox(self.tab_2)
        self.prev_checkBox_confirmDelete.setGeometry(QtCore.QRect(1060, 420, 171, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prev_checkBox_confirmDelete.setFont(font)
        self.prev_checkBox_confirmDelete.setObjectName("prev_checkBox_confirmDelete")
        self.prev_pushButton_refreshList2 = QtWidgets.QPushButton(self.tab_2)
        self.prev_pushButton_refreshList2.setGeometry(QtCore.QRect(10, 330, 181, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.prev_pushButton_refreshList2.setFont(font)
        self.prev_pushButton_refreshList2.setObjectName("prev_pushButton_refreshList2")
        self.down_textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.down_textEdit.setGeometry(QtCore.QRect(10, 366, 411, 211))
        self.down_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.down_textEdit.setObjectName("down_textEdit")
        self.checkBox_singleDownload = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_singleDownload.setGeometry(QtCore.QRect(540, 360, 161, 20))
        self.checkBox_singleDownload.setObjectName("checkBox_singleDownload")
        self.lineEdit_singleDownloadids = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_singleDownloadids.setGeometry(QtCore.QRect(450, 330, 331, 22))
        self.lineEdit_singleDownloadids.setObjectName("lineEdit_singleDownloadids")
        self.down_radioButton_normal = QtWidgets.QRadioButton(self.tab_2)
        self.down_radioButton_normal.setGeometry(QtCore.QRect(810, 330, 131, 20))
        self.down_radioButton_normal.setChecked(True)
        self.down_radioButton_normal.setObjectName("down_radioButton_normal")
        self.down_radioButton_projected = QtWidgets.QRadioButton(self.tab_2)
        self.down_radioButton_projected.setGeometry(QtCore.QRect(810, 360, 131, 20))
        self.down_radioButton_projected.setObjectName("down_radioButton_projected")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_upload = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_upload.setGeometry(QtCore.QRect(860, 120, 221, 71))
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.textEdit_codeupload = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_codeupload.setGeometry(QtCore.QRect(10, 10, 791, 271))
        self.textEdit_codeupload.setObjectName("textEdit_codeupload")
        self.pushButton_selectfile = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_selectfile.setGeometry(QtCore.QRect(860, 10, 221, 81))
        self.pushButton_selectfile.setObjectName("pushButton_selectfile")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(120, 20, 961, 551))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_3, "")
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "N3D Camera Controller"))
        self.label_2.setText(_translate("MainWindow", "N3D Camera Controller"))
        item = self.control_tableWidget_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client ID"))
        item = self.control_tableWidget_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP Address"))
        item = self.control_tableWidget_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Pi Mode"))
        item = self.control_tableWidget_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Camera Status"))
        item = self.control_tableWidget_info.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last Capture"))
        item = self.control_tableWidget_info.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Shoot N."))
        item = self.control_tableWidget_info.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Shoot P."))
        item = self.control_tableWidget_info.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CPU Temp."))
        item = self.control_tableWidget_info.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "CPU (used)"))
        item = self.control_tableWidget_info.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "RAM (used)"))
        item = self.control_tableWidget_info.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "DISK (free)"))
        self.control_pushButton_capture.setText(_translate("MainWindow", "Capture Images"))
        self.label.setText(_translate("MainWindow", "Connected Raspberry PIs (Refreshes every 5 seconds):"))
        self.control_pushButton_camReboot.setText(_translate("MainWindow", "Restart Cameras"))
        self.control_pushButton_camStop.setText(_translate("MainWindow", "Stop Cameras"))
        self.control_pushButton_refreshSysStat.setText(_translate("MainWindow", "Refresh Pi System Status"))
        self.label_5.setText(_translate("MainWindow", "List of Expected Raspberry Pis (ID):"))
        self.control_pushButton_GPIOon.setText(_translate("MainWindow", "GPIO ON"))
        self.control_pushButton_GPIOoff.setText(_translate("MainWindow", "GPIO OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), _translate("MainWindow", "Control"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Resolution"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sharpness"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contrast"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Brightness"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "ISO"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "EV"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rotation"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Shutter_Speed"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DRC"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "AWB"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "AWBG"))
        item = self.config_tableWidget_cameraConfN.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Saturation"))
        item = self.config_tableWidget_cameraConfN.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.config_tableWidget_cameraConfN.isSortingEnabled()
        self.config_tableWidget_cameraConfN.setSortingEnabled(False)
        item = self.config_tableWidget_cameraConfN.item(0, 0)
        item.setText(_translate("MainWindow", "Max Always"))
        self.config_tableWidget_cameraConfN.setSortingEnabled(__sortingEnabled)
        item = self.config_tableWidget_delayConf.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "gpio_17_on"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "capture_picam_normal"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "capture_dslr_normal"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "gpio_17_off"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "projection_on"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "capture_picam_projection"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "capture_dslr__projection"))
        item = self.config_tableWidget_delayConf.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "projection_off"))
        item = self.config_tableWidget_delayConf.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value (Seocnds)"))
        self.config_pushButton_cameraConf.setText(_translate("MainWindow", "Update Settings"))
        self.label_3.setText(_translate("MainWindow", "Normal Camera                                      Projected Camera                                                 Delay Settings"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Resolution"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sharpness"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contrast"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Brightness"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "ISO"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "EV"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Rotation"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Shutter_Speed"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "DRC"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "AWB"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "AWBG"))
        item = self.config_tableWidget_cameraConfP.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Saturation"))
        item = self.config_tableWidget_cameraConfP.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.config_tableWidget_cameraConfP.isSortingEnabled()
        self.config_tableWidget_cameraConfP.setSortingEnabled(False)
        item = self.config_tableWidget_cameraConfP.item(0, 0)
        item.setText(_translate("MainWindow", "Max Always"))
        self.config_tableWidget_cameraConfP.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("MainWindow", "Projectors\' Info"))
        self.config_pushButton_projectorSync.setText(_translate("MainWindow", "Synchronize Projectors"))
        self.config_pushButton_rebootPi.setText(_translate("MainWindow", "Reboot All Pi"))
        self.config_pushButton_shutdownPi.setText(_translate("MainWindow", "Shutdown All Pi"))
        self.config_checkBox_confirmReboot.setText(_translate("MainWindow", "Confirm reboot or shutdown."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("MainWindow", "Configuration"))
        self.prev_pushButton_preview.setText(_translate("MainWindow", "Preview"))
        self.prev_label_status.setText(_translate("MainWindow", "Preview"))
        self.prev_pushButton_refreshList.setText(_translate("MainWindow", "Refresh List"))
        self.prev_radioButton_normal.setText(_translate("MainWindow", "Normal"))
        self.prev_radioButton_projected.setText(_translate("MainWindow", "Projected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Preview"))
        self.prev_pushButton_download.setText(_translate("MainWindow", "Download"))
        self.prev_label_status_D.setText(_translate("MainWindow", "Download"))
        item = self.down_tableWidget_D.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ShootID"))
        item = self.down_tableWidget_D.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.prev_pushButton_delete.setText(_translate("MainWindow", "Delete All Pi Images"))
        self.prev_checkBox_confirmDelete.setText(_translate("MainWindow", "Confirm Delete"))
        self.prev_pushButton_refreshList2.setText(_translate("MainWindow", "Refresh List"))
        self.checkBox_singleDownload.setText(_translate("MainWindow", "Single Download"))
        self.down_radioButton_normal.setText(_translate("MainWindow", "Normal"))
        self.down_radioButton_projected.setText(_translate("MainWindow", "Projected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Download"))
        self.pushButton_upload.setText(_translate("MainWindow", "Upload"))
        self.pushButton_selectfile.setText(_translate("MainWindow", "Select File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Code Upload"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">N3D Camera Controller - V1.0</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:400; vertical-align:super;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; text-decoration: underline;\">Some instructions</span><span style=\" font-size:14pt; font-weight:400;\">:</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7pt; font-weight:400; vertical-align:super;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400; vertical-align:super;\">1. The master controller always need to use the static IP &quot;192.1683.2.10&quot; on the local network.<br />2. The local IP of Raspberry PI can be anything.<br />3. The client ID is required to be an integer number (between 1 and 999). Same ID on different raspberry pi will create issues while downloading as the communication port for the download is defined using the ID. However other communication will will not be affected with the duplicate IDs.<br />4. All the projectors should be in the following range of IPs: 192.1683.2.0 - 192.1683.2.255. The software only scan this range of IPs for the projector to minimize the scaning time.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400; vertical-align:super;\">5. Projector list is only refreshed during the software startup. So, all the projectors needed to be started before running the software or need to restart the software again after starting the projectors.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:400; vertical-align:super;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:400; vertical-align:super;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; text-decoration: underline;\">Software Developers</span><span style=\" font-size:11pt; font-weight:400;\">:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:400; vertical-align:super;\"><br /></span><span style=\" font-size:14pt; font-weight:400; vertical-align:super;\">Md. Farhanul Islam (md.farhanulislam@gmail.com)<br />Md. Shah Imran Shovon (shah_imran_sust@outlook.com)</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

